In [1]:

#task 1 

import numpy as np

food_score= np.array([[4,3,5,2.5],[3,2,1,5],[5,5,2,4],[5,4,2,1]])
print(food_score)
print(food_score[1:3])


[[4.  3.  5.  2.5]
 [3.  2.  1.  5. ]
 [5.  5.  2.  4. ]
 [5.  4.  2.  1. ]]
[[3. 2. 1. 5.]
 [5. 5. 2. 4.]]


In [2]:
#task 2 
import numpy as np 
daily_step = np.array([10000,2000,6000,7045,8001,13000,56000,6600,9000,1011])
result = daily_step[daily_step>8000]
result
    

array([10000,  8001, 13000, 56000,  9000])

In [3]:
#task 3 

import numpy as np 

ipl_score = np.array([200,600,100,152,600,588,905,455])
result = ipl_score[[1,4,6]]
result

array([600, 600, 905])

In [5]:
#task 4 

import numpy as np 

flipcart = np.array([200,100,9000,50000,600,3000])
discount = flipcart*10/100
real_price = flipcart-discount
real_price

array([  180.,    90.,  8100., 45000.,   540.,  2700.])

In [ ]:
#task 5 


import numpy as np 

rating = np.array([-5,0,6,5,-0.3,-4,-7])

rating[rating<0] = 0

rating

array([0., 0., 6., 5., 0., 0., 0.])