In [1]:
#task 1 
import numpy as np 
friend1 = np.array([5000,6000,7000,8000,9000,10000,11000])
friend2 = np.array([15000,13000,1000,2000,3000,40000,12000])

addition = friend1 + friend2
multificatio = friend1 * friend2
substraction = friend1 - friend2
divition = friend1 / friend2

In [2]:
#task 2 

import numpy as np 

import numpy as np

user_preferences = np.array([
    [5, 3, 1],
    [2, 4, 5],
    [1, 5, 4]
])

song_popularity = np.array([
    [4, 2, 1],
    [3, 5, 2],
    [1, 3, 5]
])

dot_result = user_preferences.dot(song_popularity)
matmul_result = np.matmul(user_preferences, song_popularity)

print("dot():")
print(dot_result)

print("\nmatmul():")
print(matmul_result)

dot():
[[30 28 16]
 [25 39 35]
 [23 39 31]]

matmul():
[[30 28 16]
 [25 39 35]
 [23 39 31]]


In [7]:
#task 3 

import numpy as np 

image = np.array([
    [100,600,125,456],
    [500,600,225,325],
    [125,245,265,285],
    [325,315,365,385]
    ])

trasnfer = image.T
print("transfer",trasnfer)

print("\nmean",np.mean(image))
print("standarddeviation",np.std(image))
print("varians",np.var(image))
print("meadian",np.median(image))

transfer [[100 500 125 325]
 [600 600 245 315]
 [125 225 265 365]
 [456 325 285 385]]

mean 327.5625
standarddeviation 149.2598274612094
varians 22278.49609375
meadian 320.0


In [8]:
#task 4 

import numpy as np

ratings = np.array([
    [4, 1, 0],
    [1, 3, 1],
    [0, 1, 2]
])

inverse = np.linalg.inv(ratings)
determinant = np.linalg.det(ratings)
eigenvalues, eigenvectors = np.linalg.eig(ratings)

print("Inverse:")
print(inverse)

print("\nDeterminant:")
print(determinant)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Inverse:
[[ 0.27777778 -0.11111111  0.05555556]
 [-0.11111111  0.44444444 -0.22222222]
 [ 0.05555556 -0.22222222  0.61111111]]

Determinant:
17.999999999999996

Eigenvalues:
[4.73205081 3.         1.26794919]

Eigenvectors:
[[ 0.78867513 -0.57735027  0.21132487]
 [ 0.57735027  0.57735027 -0.57735027]
 [ 0.21132487  0.57735027  0.78867513]]


In [9]:
#task 5 

import numpy as np

orders = np.array([
    [10, 20, 30, 40, 50, 60],
    [15, 25, 35, 45, 55, 65]
])

print("Original shape:", orders.shape)

# Reshape to 3 × 4
reshaped = orders.reshape(3, 4)
print("\nReshaped:")
print(reshaped)

# Flatten
flattened = reshaped.flatten()
print("\nFlattened:")
print(flattened)

# Split into two equal parts
parts = np.split(flattened, 2)

print("\nPart 1:")
print(parts[0])

print("Part 2:")
print(parts[1])

# Stack vertically
stacked = np.vstack(parts)

print("\nStacked:")
print(stacked)

Original shape: (2, 6)

Reshaped:
[[10 20 30 40]
 [50 60 15 25]
 [35 45 55 65]]

Flattened:
[10 20 30 40 50 60 15 25 35 45 55 65]

Part 1:
[10 20 30 40 50 60]
Part 2:
[15 25 35 45 55 65]

Stacked:
[[10 20 30 40 50 60]
 [15 25 35 45 55 65]]
