In [6]:
#task 2
import numpy as np 
data = np.array( [1200, 15000, 67000, 340000, 1250000])
print(data)
print(data.shape)
print(data.ndim)
print(data.dtype)



[   1200   15000   67000  340000 1250000]
(5,)
1
int64


In [ ]:
#task 3 

data1 = np.arange(101,111)
print(data1)
print(data1.size)


[101 102 103 104 105 106 107 108 109 110]
10


In [9]:
#task 4 

import numpy as np

like_matrix = np.eye(3)

print(like_matrix)

# Diagonal values (1) represent that each playlist feature is connected to itself.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
#task 5 

score = [45, 67, 120, 89, 54]

score1= np.array(score)
print(score1)
print(score1.itemsize)

[ 45  67 120  89  54]
8
